version: 2

models:
  - name: transactions
    description: "Contains one row per unique transaction."
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: visitor_id
        tests:
          - relationships:
              to: ref('users')
              field: visitor_id

  - name: users
    description: "Contains one row per unique user."
    columns:
      - name: visitor_id
        tests:
          - unique
          - not_null

  - name: products
    description: "Contains one row per unique product."
    columns:
      - name: item_id
        tests:
          - unique
          - not_null